version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: dev_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mongodb:
  #   image: mongo:6
  #   container_name: dev_mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: devuser
  #     MONGO_INITDB_ROOT_PASSWORD: devpassword
  #   volumes:
  #     - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: dev_redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
